#!/bin/bash

# URL to be pinged
URL="http URL"

# Send a request to the URL and get the HTTP status code
HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")

# Display the status
if [ "$HTTP_STATUS" -eq 200 ]; then
    echo "URL is reachable. Status: $HTTP_STATUS"
else
    echo "URL is not reachable. Status: $HTTP_STATUS"
fi



#!/bin/bash

# URL to be pinged
URL="URL"

# Send a request to the URL and get the HTTP status code
HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")

# Display the status
if [ "$HTTP_STATUS" -eq 200 ]; then
    echo "URL is reachable. Status: $HTTP_STATUS"
else
    echo "URL is not reachable. Status: $HTTP_STATUS"
fi
